In [7]:
import os
import tensorflow as tf
import cProfile
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
#by default in >v2.0, its ON
tf.executing_eagerly()

True

In [4]:
x = [[2.0]]
m = tf.matmul(x,x)
print("hello {}".format(m))

hello [[4.]]


In [14]:
# np array to tf.Tensor -> tf.math
# tf.Tensor to np array -> tf.Tensor.numpy to ndarray

# numpy to tensor
aa=np.array([[1,2]])
a = tf.constant(aa) #or tf.constant([[1,2]])
print(a)

# broadcasting support
b = tf.add(a,1)
print(b)

# operator overloading allowed
print(a*b)

# use numpy values
c = np.multiply(a,b)
print(c)

# tensor to numpy
print(a.numpy())

# number to tensor
tensor = tf.convert_to_tensor(5)
print(tensor)

tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
tf.Tensor([[2 6]], shape=(1, 2), dtype=int32)
[[2 6]]
[[1 2]]


In [19]:
# EAGER TRAINING
#computing gradients
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss= w*w
    
#gardient of loss wrt to w    
grad = tape.gradient(loss,w)
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
