In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import timeit
from datetime import datetime
from tensorflow import keras
from tensorflow.keras import layers
import array

%load_ext tensorboard

print("Using TensorFlow version %s" % tf.__version__)

Using TensorFlow version 2.3.0


In [4]:
from tensorflow import keras as keras

In [5]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Dense
from tensorflow.keras.layers import Flatten, LSTM
from tensorflow.keras.layers import GlobalMaxPooling1D
from tensorflow.keras.models import Model
#from tensorflow.keras.layers.Embedding import Embedding
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Input
#from tensorflow.keras.layers.merge import Concatenate
from tensorflow.keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [6]:
X = np.array([x+1 for x in range(20)])
Y = np.array([y * 15 for y in X])

print(X)
print(Y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255 270
 285 300]


In [7]:
X = array(X).reshape(20, 1, 1) #batch_size, time-steps, features

In [31]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 50)                10400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________
None


In [32]:
model.fit(X, Y, epochs=2000, validation_split=0.2, batch_size=5)

Epoch 1/2000
4/4 [==============================] - 1s 160ms/step - loss: 21102.3730 - val_loss: 77416.6016
Epoch 2/2000
4/4 [==============================] - 0s 9ms/step - loss: 21072.6367 - val_loss: 77298.1406
Epoch 3/2000
4/4 [==============================] - 0s 10ms/step - loss: 21044.7734 - val_loss: 77185.8203
Epoch 4/2000
4/4 [==============================] - 0s 10ms/step - loss: 21016.7734 - val_loss: 77072.2188
Epoch 5/2000
4/4 [==============================] - 0s 11ms/step - loss: 20989.8906 - val_loss: 76960.0859
Epoch 6/2000
4/4 [==============================] - 0s 12ms/step - loss: 20960.9023 - val_loss: 76849.7656
Epoch 7/2000
4/4 [==============================] - 0s 10ms/step - loss: 20931.7500 - val_loss: 76732.8828
Epoch 8/2000
4/4 [==============================] - 0s 10ms/step - loss: 20902.2051 - val_loss: 76609.8672
Epoch 9/2000
4/4 [==============================] - 0s 9ms/step - loss: 20871.9863 - val_loss: 76492.4062
Epoch 10/2000
4/4 [===================

Epoch 77/2000
4/4 [==============================] - 0s 11ms/step - loss: 13477.8916 - val_loss: 48811.4609
Epoch 78/2000
4/4 [==============================] - 0s 10ms/step - loss: 13311.8389 - val_loss: 48213.2109
Epoch 79/2000
4/4 [==============================] - 0s 9ms/step - loss: 13132.6797 - val_loss: 47590.3672
Epoch 80/2000
4/4 [==============================] - 0s 10ms/step - loss: 12958.2461 - val_loss: 46945.1875
Epoch 81/2000
4/4 [==============================] - 0s 9ms/step - loss: 12774.5342 - val_loss: 46309.1562
Epoch 82/2000
4/4 [==============================] - 0s 10ms/step - loss: 12588.9492 - val_loss: 45648.3281
Epoch 83/2000
4/4 [==============================] - 0s 12ms/step - loss: 12409.9199 - val_loss: 44999.0586
Epoch 84/2000
4/4 [==============================] - 0s 11ms/step - loss: 12217.7256 - val_loss: 44391.3320
Epoch 85/2000
4/4 [==============================] - 0s 9ms/step - loss: 12059.1406 - val_loss: 43781.6484
Epoch 86/2000
4/4 [============

4/4 [==============================] - 0s 13ms/step - loss: 82.2472 - val_loss: 530.6674
Epoch 230/2000
4/4 [==============================] - 0s 11ms/step - loss: 78.8574 - val_loss: 511.8506
Epoch 231/2000
4/4 [==============================] - 0s 13ms/step - loss: 74.6615 - val_loss: 494.3171
Epoch 232/2000
4/4 [==============================] - 0s 18ms/step - loss: 71.0640 - val_loss: 475.7943
Epoch 233/2000
4/4 [==============================] - 0s 21ms/step - loss: 67.6200 - val_loss: 457.2656
Epoch 234/2000
4/4 [==============================] - 0s 17ms/step - loss: 64.3794 - val_loss: 438.2121
Epoch 235/2000
4/4 [==============================] - 0s 15ms/step - loss: 60.4653 - val_loss: 420.5482
Epoch 236/2000
4/4 [==============================] - 0s 15ms/step - loss: 56.7532 - val_loss: 403.2802
Epoch 237/2000
4/4 [==============================] - 0s 17ms/step - loss: 54.1705 - val_loss: 385.7971
Epoch 238/2000
4/4 [==============================] - 0s 16ms/step - loss: 50.4

Epoch 389/2000
4/4 [==============================] - 0s 9ms/step - loss: 4.2271 - val_loss: 42.3857
Epoch 390/2000
4/4 [==============================] - 0s 9ms/step - loss: 4.2163 - val_loss: 42.5889
Epoch 391/2000
4/4 [==============================] - 0s 10ms/step - loss: 4.1997 - val_loss: 42.8519
Epoch 392/2000
4/4 [==============================] - 0s 10ms/step - loss: 4.1973 - val_loss: 43.2921
Epoch 393/2000
4/4 [==============================] - 0s 10ms/step - loss: 4.1880 - val_loss: 43.7574
Epoch 394/2000
4/4 [==============================] - 0s 11ms/step - loss: 4.1844 - val_loss: 44.1913
Epoch 395/2000
4/4 [==============================] - 0s 10ms/step - loss: 4.1596 - val_loss: 44.4505
Epoch 396/2000
4/4 [==============================] - 0s 13ms/step - loss: 4.1542 - val_loss: 44.8114
Epoch 397/2000
4/4 [==============================] - 0s 10ms/step - loss: 4.1502 - val_loss: 45.0570
Epoch 398/2000
4/4 [==============================] - 0s 9ms/step - loss: 4.1399 - v

4/4 [==============================] - 0s 14ms/step - loss: 3.0055 - val_loss: 38.6047
Epoch 550/2000
4/4 [==============================] - 0s 13ms/step - loss: 2.9987 - val_loss: 38.3012
Epoch 551/2000
4/4 [==============================] - 0s 13ms/step - loss: 2.9888 - val_loss: 38.1882
Epoch 552/2000
4/4 [==============================] - 0s 12ms/step - loss: 2.9831 - val_loss: 38.1492
Epoch 553/2000
4/4 [==============================] - 0s 12ms/step - loss: 2.9826 - val_loss: 38.1954
Epoch 554/2000
4/4 [==============================] - 0s 12ms/step - loss: 2.9785 - val_loss: 38.0374
Epoch 555/2000
4/4 [==============================] - 0s 16ms/step - loss: 2.9719 - val_loss: 38.1795
Epoch 556/2000
4/4 [==============================] - 0s 15ms/step - loss: 2.9690 - val_loss: 38.0901
Epoch 557/2000
4/4 [==============================] - 0s 15ms/step - loss: 2.9583 - val_loss: 37.4032
Epoch 558/2000
4/4 [==============================] - 0s 15ms/step - loss: 2.9501 - val_loss: 36.

4/4 [==============================] - 0s 18ms/step - loss: 2.2857 - val_loss: 28.4468
Epoch 710/2000
4/4 [==============================] - 0s 18ms/step - loss: 2.2799 - val_loss: 27.9138
Epoch 711/2000
4/4 [==============================] - 0s 18ms/step - loss: 2.2794 - val_loss: 27.8058
Epoch 712/2000
4/4 [==============================] - 0s 20ms/step - loss: 2.2753 - val_loss: 27.8300
Epoch 713/2000
4/4 [==============================] - 0s 19ms/step - loss: 2.2684 - val_loss: 27.9885
Epoch 714/2000
4/4 [==============================] - 0s 17ms/step - loss: 2.2695 - val_loss: 28.1934
Epoch 715/2000
4/4 [==============================] - 0s 20ms/step - loss: 2.2641 - val_loss: 28.2192
Epoch 716/2000
4/4 [==============================] - 0s 18ms/step - loss: 2.2612 - val_loss: 28.1466
Epoch 717/2000
4/4 [==============================] - 0s 19ms/step - loss: 2.2661 - val_loss: 27.8756
Epoch 718/2000
4/4 [==============================] - 0s 20ms/step - loss: 2.2580 - val_loss: 27.

4/4 [==============================] - 0s 9ms/step - loss: 1.8666 - val_loss: 22.3814
Epoch 871/2000
4/4 [==============================] - 0s 8ms/step - loss: 1.8654 - val_loss: 22.1822
Epoch 872/2000
4/4 [==============================] - 0s 7ms/step - loss: 1.8685 - val_loss: 22.1808
Epoch 873/2000
4/4 [==============================] - 0s 6ms/step - loss: 1.8617 - val_loss: 21.6699
Epoch 874/2000
4/4 [==============================] - 0s 6ms/step - loss: 1.8695 - val_loss: 21.3403
Epoch 875/2000
4/4 [==============================] - 0s 6ms/step - loss: 1.8644 - val_loss: 21.2255
Epoch 876/2000
4/4 [==============================] - 0s 6ms/step - loss: 1.8633 - val_loss: 20.9601
Epoch 877/2000
4/4 [==============================] - 0s 7ms/step - loss: 1.8583 - val_loss: 20.8804
Epoch 878/2000
4/4 [==============================] - 0s 7ms/step - loss: 1.8633 - val_loss: 20.7279
Epoch 879/2000
4/4 [==============================] - 0s 7ms/step - loss: 1.8538 - val_loss: 20.9241
Epoch

4/4 [==============================] - 0s 16ms/step - loss: 1.4138 - val_loss: 19.5354
Epoch 1032/2000
4/4 [==============================] - 0s 19ms/step - loss: 1.4152 - val_loss: 19.7428
Epoch 1033/2000
4/4 [==============================] - 0s 16ms/step - loss: 1.4182 - val_loss: 19.9176
Epoch 1034/2000
4/4 [==============================] - 0s 16ms/step - loss: 1.4163 - val_loss: 19.8151
Epoch 1035/2000
4/4 [==============================] - 0s 17ms/step - loss: 1.4050 - val_loss: 19.2985
Epoch 1036/2000
4/4 [==============================] - 0s 16ms/step - loss: 1.4029 - val_loss: 18.9909
Epoch 1037/2000
4/4 [==============================] - 0s 17ms/step - loss: 1.3944 - val_loss: 18.7872
Epoch 1038/2000
4/4 [==============================] - 0s 16ms/step - loss: 1.3899 - val_loss: 18.5870
Epoch 1039/2000
4/4 [==============================] - 0s 15ms/step - loss: 1.3844 - val_loss: 18.4933
Epoch 1040/2000
4/4 [==============================] - 0s 18ms/step - loss: 1.3794 - val_

4/4 [==============================] - 0s 15ms/step - loss: 0.8565 - val_loss: 12.0568
Epoch 1190/2000
4/4 [==============================] - 0s 22ms/step - loss: 0.8561 - val_loss: 11.8990
Epoch 1191/2000
4/4 [==============================] - 0s 11ms/step - loss: 0.8405 - val_loss: 11.1187
Epoch 1192/2000
4/4 [==============================] - 0s 10ms/step - loss: 0.8444 - val_loss: 10.3674
Epoch 1193/2000
4/4 [==============================] - 0s 9ms/step - loss: 0.8332 - val_loss: 9.9146
Epoch 1194/2000
4/4 [==============================] - 0s 9ms/step - loss: 0.8292 - val_loss: 9.7955
Epoch 1195/2000
4/4 [==============================] - 0s 10ms/step - loss: 0.8269 - val_loss: 9.6957
Epoch 1196/2000
4/4 [==============================] - 0s 18ms/step - loss: 0.8258 - val_loss: 9.7185
Epoch 1197/2000
4/4 [==============================] - 0s 18ms/step - loss: 0.8234 - val_loss: 10.0755
Epoch 1198/2000
4/4 [==============================] - 0s 19ms/step - loss: 0.8125 - val_loss: 

4/4 [==============================] - 0s 8ms/step - loss: 0.5390 - val_loss: 3.7038
Epoch 1350/2000
4/4 [==============================] - 0s 11ms/step - loss: 0.5327 - val_loss: 3.9741
Epoch 1351/2000
4/4 [==============================] - 0s 9ms/step - loss: 0.5135 - val_loss: 4.5449
Epoch 1352/2000
4/4 [==============================] - 0s 11ms/step - loss: 0.5005 - val_loss: 5.1624
Epoch 1353/2000
4/4 [==============================] - 0s 17ms/step - loss: 0.5082 - val_loss: 5.6734
Epoch 1354/2000
4/4 [==============================] - 0s 19ms/step - loss: 0.5224 - val_loss: 5.7459
Epoch 1355/2000
4/4 [==============================] - 0s 27ms/step - loss: 0.5188 - val_loss: 5.5258
Epoch 1356/2000
4/4 [==============================] - 0s 18ms/step - loss: 0.5097 - val_loss: 5.1772
Epoch 1357/2000
4/4 [==============================] - 0s 14ms/step - loss: 0.5049 - val_loss: 4.8540
Epoch 1358/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.4982 - val_loss: 4.657

4/4 [==============================] - 0s 19ms/step - loss: 0.3977 - val_loss: 2.1584
Epoch 1510/2000
4/4 [==============================] - 0s 21ms/step - loss: 0.3970 - val_loss: 2.1950
Epoch 1511/2000
4/4 [==============================] - 0s 16ms/step - loss: 0.3991 - val_loss: 2.0678
Epoch 1512/2000
4/4 [==============================] - 0s 19ms/step - loss: 0.3966 - val_loss: 2.2062
Epoch 1513/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.3951 - val_loss: 2.3388
Epoch 1514/2000
4/4 [==============================] - 0s 17ms/step - loss: 0.3919 - val_loss: 2.3665
Epoch 1515/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.3907 - val_loss: 2.3513
Epoch 1516/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.3896 - val_loss: 2.5219
Epoch 1517/2000
4/4 [==============================] - 0s 16ms/step - loss: 0.3902 - val_loss: 2.6413
Epoch 1518/2000
4/4 [==============================] - 0s 17ms/step - loss: 0.3893 - val_loss: 2.7

4/4 [==============================] - 0s 14ms/step - loss: 0.3338 - val_loss: 1.0818
Epoch 1670/2000
4/4 [==============================] - 0s 16ms/step - loss: 0.3326 - val_loss: 1.1511
Epoch 1671/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.3256 - val_loss: 1.3307
Epoch 1672/2000
4/4 [==============================] - 0s 19ms/step - loss: 0.3243 - val_loss: 1.6692
Epoch 1673/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.3257 - val_loss: 1.9590
Epoch 1674/2000
4/4 [==============================] - 0s 14ms/step - loss: 0.3374 - val_loss: 2.0682
Epoch 1675/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.3349 - val_loss: 1.7230
Epoch 1676/2000
4/4 [==============================] - 0s 15ms/step - loss: 0.3170 - val_loss: 1.2042
Epoch 1677/2000
4/4 [==============================] - 0s 16ms/step - loss: 0.3214 - val_loss: 0.9442
Epoch 1678/2000
4/4 [==============================] - 0s 16ms/step - loss: 0.3375 - val_loss: 0.8

4/4 [==============================] - 0s 11ms/step - loss: 0.2651 - val_loss: 0.8241
Epoch 1830/2000
4/4 [==============================] - 0s 11ms/step - loss: 0.2634 - val_loss: 0.8920
Epoch 1831/2000
4/4 [==============================] - 0s 12ms/step - loss: 0.2642 - val_loss: 0.8642
Epoch 1832/2000
4/4 [==============================] - 0s 13ms/step - loss: 0.2631 - val_loss: 0.7897
Epoch 1833/2000
4/4 [==============================] - 0s 12ms/step - loss: 0.2637 - val_loss: 0.7778
Epoch 1834/2000
4/4 [==============================] - 0s 12ms/step - loss: 0.2638 - val_loss: 0.7637
Epoch 1835/2000
4/4 [==============================] - 0s 10ms/step - loss: 0.2621 - val_loss: 0.8375
Epoch 1836/2000
4/4 [==============================] - 0s 13ms/step - loss: 0.2685 - val_loss: 0.9199
Epoch 1837/2000
4/4 [==============================] - 0s 12ms/step - loss: 0.2623 - val_loss: 0.6525
Epoch 1838/2000
4/4 [==============================] - 0s 11ms/step - loss: 0.2634 - val_loss: 0.6

4/4 [==============================] - 0s 17ms/step - loss: 0.2167 - val_loss: 0.4201
Epoch 1990/2000
4/4 [==============================] - 0s 17ms/step - loss: 0.2139 - val_loss: 0.1591
Epoch 1991/2000
4/4 [==============================] - 0s 18ms/step - loss: 0.2272 - val_loss: 0.1167
Epoch 1992/2000
4/4 [==============================] - 0s 17ms/step - loss: 0.2309 - val_loss: 0.2088
Epoch 1993/2000
4/4 [==============================] - 0s 16ms/step - loss: 0.2112 - val_loss: 0.4909
Epoch 1994/2000
4/4 [==============================] - 0s 19ms/step - loss: 0.2146 - val_loss: 0.7471
Epoch 1995/2000
4/4 [==============================] - 0s 19ms/step - loss: 0.2253 - val_loss: 0.6474
Epoch 1996/2000
4/4 [==============================] - 0s 20ms/step - loss: 0.2147 - val_loss: 0.4587
Epoch 1997/2000
4/4 [==============================] - 0s 19ms/step - loss: 0.2083 - val_loss: 0.3620
Epoch 1998/2000
4/4 [==============================] - 0s 20ms/step - loss: 0.2079 - val_loss: 0.2

In [33]:
#stacked LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(1, 1)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 1, 50)             10400     
_________________________________________________________________
lstm_3 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 51        
Total params: 30,651
Trainable params: 30,651
Non-trainable params: 0
_________________________________________________________________
None


In [34]:
history = model.fit(X, Y, epochs=500, validation_split=0.2, verbose=1, batch_size=5)

Epoch 1/500
4/4 [==============================] - 1s 228ms/step - loss: 21020.3223 - val_loss: 77177.5625
Epoch 2/500
4/4 [==============================] - 0s 9ms/step - loss: 21008.8027 - val_loss: 77133.3125
Epoch 3/500
4/4 [==============================] - 0s 10ms/step - loss: 20996.9551 - val_loss: 77083.6719
Epoch 4/500
4/4 [==============================] - 0s 10ms/step - loss: 20981.5781 - val_loss: 77026.8750
Epoch 5/500
4/4 [==============================] - 0s 10ms/step - loss: 20967.8223 - val_loss: 76956.7031
Epoch 6/500
4/4 [==============================] - 0s 10ms/step - loss: 20948.9844 - val_loss: 76871.4375
Epoch 7/500
4/4 [==============================] - 0s 10ms/step - loss: 20925.5527 - val_loss: 76770.5000
Epoch 8/500
4/4 [==============================] - 0s 10ms/step - loss: 20902.1328 - val_loss: 76641.2812
Epoch 9/500
4/4 [==============================] - 0s 12ms/step - loss: 20870.2891 - val_loss: 76483.3438
Epoch 10/500
4/4 [============================

Epoch 159/500
4/4 [==============================] - 0s 23ms/step - loss: 44.1271 - val_loss: 164.0822
Epoch 160/500
4/4 [==============================] - 0s 19ms/step - loss: 43.6793 - val_loss: 164.2466
Epoch 161/500
4/4 [==============================] - 0s 19ms/step - loss: 43.3221 - val_loss: 167.4476
Epoch 162/500
4/4 [==============================] - 0s 20ms/step - loss: 42.9252 - val_loss: 174.1579
Epoch 163/500
4/4 [==============================] - 0s 19ms/step - loss: 42.5803 - val_loss: 182.6608
Epoch 164/500
4/4 [==============================] - 0s 18ms/step - loss: 42.2415 - val_loss: 189.0916
Epoch 165/500
4/4 [==============================] - 0s 17ms/step - loss: 42.0583 - val_loss: 196.1458
Epoch 166/500
4/4 [==============================] - 0s 20ms/step - loss: 42.0688 - val_loss: 200.1706
Epoch 167/500
4/4 [==============================] - 0s 18ms/step - loss: 41.7100 - val_loss: 190.4638
Epoch 168/500
4/4 [==============================] - 0s 18ms/step - loss:

4/4 [==============================] - 0s 18ms/step - loss: 9.0507 - val_loss: 31.0869
Epoch 319/500
4/4 [==============================] - 0s 21ms/step - loss: 8.9813 - val_loss: 26.7411
Epoch 320/500
4/4 [==============================] - 0s 20ms/step - loss: 9.0870 - val_loss: 26.0149
Epoch 321/500
4/4 [==============================] - 0s 18ms/step - loss: 8.9354 - val_loss: 28.7810
Epoch 322/500
4/4 [==============================] - 0s 19ms/step - loss: 8.6982 - val_loss: 32.5440
Epoch 323/500
4/4 [==============================] - 0s 20ms/step - loss: 8.5727 - val_loss: 33.9264
Epoch 324/500
4/4 [==============================] - 0s 19ms/step - loss: 8.4139 - val_loss: 31.7539
Epoch 325/500
4/4 [==============================] - 0s 21ms/step - loss: 8.3066 - val_loss: 28.6277
Epoch 326/500
4/4 [==============================] - 0s 21ms/step - loss: 8.2958 - val_loss: 27.9852
Epoch 327/500
4/4 [==============================] - 0s 19ms/step - loss: 8.1635 - val_loss: 29.8456
Epoc

Epoch 481/500
4/4 [==============================] - 0s 18ms/step - loss: 1.1161 - val_loss: 2.2807
Epoch 482/500
4/4 [==============================] - 0s 20ms/step - loss: 1.1050 - val_loss: 2.2374
Epoch 483/500
4/4 [==============================] - 0s 18ms/step - loss: 1.0981 - val_loss: 2.2968
Epoch 484/500
4/4 [==============================] - 0s 19ms/step - loss: 1.0893 - val_loss: 2.4310
Epoch 485/500
4/4 [==============================] - 0s 18ms/step - loss: 1.0755 - val_loss: 2.3185
Epoch 486/500
4/4 [==============================] - 0s 18ms/step - loss: 1.0585 - val_loss: 1.7424
Epoch 487/500
4/4 [==============================] - 0s 18ms/step - loss: 1.0864 - val_loss: 1.4489
Epoch 488/500
4/4 [==============================] - 0s 19ms/step - loss: 1.0590 - val_loss: 1.6431
Epoch 489/500
4/4 [==============================] - 0s 18ms/step - loss: 1.0379 - val_loss: 1.8494
Epoch 490/500
4/4 [==============================] - 0s 18ms/step - loss: 1.0232 - val_loss: 1.9530


In [35]:
test_input = array([30])
test_input = test_input.reshape((1, 1, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[450.37497]]


In [43]:
# one to one with multiple features
nums = 25

X1 = list()
X2 = list()
X = list()
Y = list()

X1 = np.array([(x+1)*2 for x in range(25)])
X2 = np.array([(x+1)*3 for x in range(25)])
Y = np.array([x1*x2 for x1,x2 in zip(X1,X2)])

print(X1)
print(X2)
print(Y)
X = np.column_stack((X1, X2))
print(X)
X = array(X).reshape(25, 1, 2)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75]
[   6   24   54   96  150  216  294  384  486  600  726  864 1014 1176
 1350 1536 1734 1944 2166 2400 2646 2904 3174 3456 3750]
[[ 2  3]
 [ 4  6]
 [ 6  9]
 [ 8 12]
 [10 15]
 [12 18]
 [14 21]
 [16 24]
 [18 27]
 [20 30]
 [22 33]
 [24 36]
 [26 39]
 [28 42]
 [30 45]
 [32 48]
 [34 51]
 [36 54]
 [38 57]
 [40 60]
 [42 63]
 [44 66]
 [46 69]
 [48 72]
 [50 75]]


In [44]:
model = Sequential()
model.add(LSTM(80, activation='relu', input_shape=(1, 2)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 80)                26560     
_________________________________________________________________
dense_7 (Dense)              (None, 10)                810       
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 11        
Total params: 27,381
Trainable params: 27,381
Non-trainable params: 0
_________________________________________________________________
None


In [45]:
model.fit(X, Y, epochs=100, validation_split=0.2, batch_size=5)

Epoch 1/100
4/4 [==============================] - 0s 45ms/step - loss: 1299383.2500 - val_loss: 10291243.0000
Epoch 2/100
4/4 [==============================] - 0s 7ms/step - loss: 1298296.6250 - val_loss: 10285802.0000
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 1297399.5000 - val_loss: 10279183.0000
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 1296276.7500 - val_loss: 10270326.0000
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 1294556.0000 - val_loss: 10258542.0000
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 1292281.2500 - val_loss: 10244703.0000
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 1289642.3750 - val_loss: 10228926.0000
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 1286855.2500 - val_loss: 10210426.0000
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 1283514.8750 - val_loss: 10189971.0000
Epoch 10/

Epoch 76/100
4/4 [==============================] - 0s 5ms/step - loss: 114302.3516 - val_loss: 2141602.2500
Epoch 77/100
4/4 [==============================] - 0s 5ms/step - loss: 105993.6016 - val_loss: 2056186.0000
Epoch 78/100
4/4 [==============================] - 0s 5ms/step - loss: 100315.1719 - val_loss: 1970255.7500
Epoch 79/100
4/4 [==============================] - 0s 4ms/step - loss: 93072.0859 - val_loss: 1895885.0000
Epoch 80/100
4/4 [==============================] - 0s 4ms/step - loss: 88670.2969 - val_loss: 1819994.7500
Epoch 81/100
4/4 [==============================] - 0s 5ms/step - loss: 82717.0156 - val_loss: 1754215.2500
Epoch 82/100
4/4 [==============================] - 0s 4ms/step - loss: 79505.1641 - val_loss: 1683768.6250
Epoch 83/100
4/4 [==============================] - 0s 4ms/step - loss: 74445.1875 - val_loss: 1625045.1250
Epoch 84/100
4/4 [==============================] - 0s 4ms/step - loss: 70704.3281 - val_loss: 1570035.3750
Epoch 85/100
4/4 [=======

In [46]:
test_input = array([55,80])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[2611.701]]


In [47]:
# via stacked LSTM
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(1, 2)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_7 (LSTM)                (None, 1, 200)            162400    
_________________________________________________________________
lstm_8 (LSTM)                (None, 1, 100)            120400    
_________________________________________________________________
lstm_9 (LSTM)                (None, 1, 50)             30200     
_________________________________________________________________
lstm_10 (LSTM)               (None, 25)                7600      
_________________________________________________________________
dense_9 (Dense)              (None, 20)                520       
_________________________________________________________________
dense_10 (Dense)             (None, 10)                210       
_________________________________________________________________
dense_11 (Dense)             (None, 1)                

In [49]:
history = model.fit(X, Y, epochs=100, validation_split=0.1, verbose=1, batch_size=3)

test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
8/8 [==============================] - 0s 8ms/step - loss: 324.5717 - val_loss: 9896.1729
Epoch 2/100
8/8 [==============================] - 0s 5ms/step - loss: 933.4037 - val_loss: 8361.7969
Epoch 3/100
8/8 [==============================] - 0s 5ms/step - loss: 271.2434 - val_loss: 11604.1572
Epoch 4/100
8/8 [==============================] - 0s 5ms/step - loss: 183.9642 - val_loss: 10757.1865
Epoch 5/100
8/8 [==============================] - 0s 5ms/step - loss: 176.1675 - val_loss: 4890.7017
Epoch 6/100
8/8 [==============================] - 0s 5ms/step - loss: 248.2892 - val_loss: 5970.9395
Epoch 7/100
8/8 [==============================] - 0s 5ms/step - loss: 211.7718 - val_loss: 8672.3115
Epoch 8/100
8/8 [==============================] - 0s 5ms/step - loss: 148.2747 - val_loss: 15760.7236
Epoch 9/100
8/8 [==============================] - ETA: 0s - loss: 303.353 - 0s 5ms/step - loss: 552.0873 - val_loss: 23508.7871
Epoch 10/100
8/8 [==============================] - 

In [50]:
# in one to one, sample consists of one time stamp with one or more features
# many to one 
X = np.array([x+1 for x in range(45)])
print(X)
X = X.reshape(15,3,1)
print(X)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


In [51]:
Y = list()
for x in X:
    Y.append(x.sum())

Y = np.array(Y)
print(Y)

[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


In [53]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)

test_input = array([50,51,52])
test_input = test_input.reshape((1, 3, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
1/1 [==============================] - 0s 193ms/step - loss: 4016.5359 - val_loss: 14924.7432
Epoch 2/100
1/1 [==============================] - 0s 17ms/step - loss: 3991.7356 - val_loss: 14831.5000
Epoch 3/100
1/1 [==============================] - 0s 19ms/step - loss: 3967.5129 - val_loss: 14740.9189
Epoch 4/100
1/1 [==============================] - 0s 18ms/step - loss: 3943.7092 - val_loss: 14651.8721
Epoch 5/100
1/1 [==============================] - 0s 15ms/step - loss: 3920.2644 - val_loss: 14563.8906
Epoch 6/100
1/1 [==============================] - 0s 17ms/step - loss: 3897.1123 - val_loss: 14476.8545
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 3874.2031 - val_loss: 14390.6338
Epoch 8/100
1/1 [==============================] - 0s 15ms/step - loss: 3851.4900 - val_loss: 14305.0830
Epoch 9/100
1/1 [==============================] - 0s 15ms/step - loss: 3828.9277 - val_loss: 14220.0547
Epoch 10/100
1/1 [==============================] - 0s

In [55]:
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(3, 1)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
1/1 [==============================] - 0s 464ms/step - loss: 4045.7480 - val_loss: 15177.7002
Epoch 2/100
1/1 [==============================] - 0s 17ms/step - loss: 4043.9753 - val_loss: 15170.8135
Epoch 3/100
1/1 [==============================] - 0s 19ms/step - loss: 4041.9871 - val_loss: 15161.4404
Epoch 4/100
1/1 [==============================] - 0s 18ms/step - loss: 4039.8604 - val_loss: 15149.0420
Epoch 5/100
1/1 [==============================] - 0s 17ms/step - loss: 4037.1536 - val_loss: 15130.2109
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 4033.4285 - val_loss: 15100.2861
Epoch 7/100
1/1 [==============================] - 0s 16ms/step - loss: 4028.0781 - val_loss: 15050.7266
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 4020.0449 - val_loss: 14971.7158
Epoch 9/100
1/1 [==============================] - 0s 19ms/step - loss: 4007.4719 - val_loss: 14856.0703
Epoch 10/100
1/1 [==============================] - 0s

Epoch 81/100
1/1 [==============================] - 0s 17ms/step - loss: 6.1440 - val_loss: 0.0535
Epoch 82/100
1/1 [==============================] - 0s 15ms/step - loss: 5.6271 - val_loss: 0.0359
Epoch 83/100
1/1 [==============================] - 0s 16ms/step - loss: 5.1449 - val_loss: 0.0738
Epoch 84/100
1/1 [==============================] - 0s 14ms/step - loss: 4.7525 - val_loss: 0.2428
Epoch 85/100
1/1 [==============================] - 0s 14ms/step - loss: 4.4469 - val_loss: 0.4827
Epoch 86/100
1/1 [==============================] - 0s 15ms/step - loss: 4.1845 - val_loss: 0.6876
Epoch 87/100
1/1 [==============================] - 0s 14ms/step - loss: 3.9429 - val_loss: 0.8350
Epoch 88/100
1/1 [==============================] - 0s 13ms/step - loss: 3.7408 - val_loss: 1.1197
Epoch 89/100
1/1 [==============================] - 0s 17ms/step - loss: 3.5521 - val_loss: 1.5417
Epoch 90/100
1/1 [==============================] - 0s 17ms/step - loss: 3.3712 - val_loss: 2.0004
Epoch 91/1

In [56]:
from tensorflow.keras.layers import Bidirectional

In [58]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
1/1 [==============================] - 0s 281ms/step - loss: 3977.8601 - val_loss: 14636.7344
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 3928.9883 - val_loss: 14452.6533
Epoch 3/100
1/1 [==============================] - 0s 14ms/step - loss: 3880.7861 - val_loss: 14270.3291
Epoch 4/100
1/1 [==============================] - 0s 18ms/step - loss: 3832.9668 - val_loss: 14089.3662
Epoch 5/100
1/1 [==============================] - 0s 17ms/step - loss: 3785.4551 - val_loss: 13909.4580
Epoch 6/100
1/1 [==============================] - 0s 19ms/step - loss: 3738.1160 - val_loss: 13730.3369
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 3690.8230 - val_loss: 13551.1729
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 3643.4802 - val_loss: 13371.9482
Epoch 9/100
1/1 [==============================] - 0s 13ms/step - loss: 3595.9792 - val_loss: 13192.3584
Epoch 10/100
1/1 [==============================] - 0s

Epoch 80/100
1/1 [==============================] - 0s 15ms/step - loss: 23.7738 - val_loss: 4.8149
Epoch 81/100
1/1 [==============================] - 0s 16ms/step - loss: 22.0716 - val_loss: 2.6750
Epoch 82/100
1/1 [==============================] - 0s 16ms/step - loss: 20.2970 - val_loss: 1.0063
Epoch 83/100
1/1 [==============================] - 0s 17ms/step - loss: 18.5612 - val_loss: 0.0925
Epoch 84/100
1/1 [==============================] - 0s 17ms/step - loss: 16.9666 - val_loss: 0.2201
Epoch 85/100
1/1 [==============================] - 0s 18ms/step - loss: 15.6073 - val_loss: 1.7334
Epoch 86/100
1/1 [==============================] - 0s 16ms/step - loss: 14.5717 - val_loss: 5.0147
Epoch 87/100
1/1 [==============================] - 0s 15ms/step - loss: 13.9407 - val_loss: 9.6286
Epoch 88/100
1/1 [==============================] - 0s 18ms/step - loss: 13.7092 - val_loss: 13.7898
Epoch 89/100
1/1 [==============================] - 0s 17ms/step - loss: 13.6863 - val_loss: 16.709

In [61]:
# many to one with multiple features
X1 = np.array([x+3 for x in range(0, 135, 3)])
print(X1)

X2 = np.array([x+5 for x in range(0, 225, 5)])
print(X2)

X = np.column_stack((X1, X2))
print(X)

X = array(X).reshape(15, 3, 2)
print(X)

[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225]
[[  3   5]
 [  6  10]
 [  9  15]
 [ 12  20]
 [ 15  25]
 [ 18  30]
 [ 21  35]
 [ 24  40]
 [ 27  45]
 [ 30  50]
 [ 33  55]
 [ 36  60]
 [ 39  65]
 [ 42  70]
 [ 45  75]
 [ 48  80]
 [ 51  85]
 [ 54  90]
 [ 57  95]
 [ 60 100]
 [ 63 105]
 [ 66 110]
 [ 69 115]
 [ 72 120]
 [ 75 125]
 [ 78 130]
 [ 81 135]
 [ 84 140]
 [ 87 145]
 [ 90 150]
 [ 93 155]
 [ 96 160]
 [ 99 165]
 [102 170]
 [105 175]
 [108 180]
 [111 185]
 [114 190]
 [117 195]
 [120 200]
 [123 205]
 [126 210]
 [129 215]
 [132 220]
 [135 225]]
[[[  3   5]
  [  6  10]
  [  9  15]]

 [[ 12  20]
  [ 15  25]
  [ 18  30]]

 [[ 21  35]
  [ 24  40]
  [ 27  45]]

 [[ 30  50]
  [ 33  55

In [74]:
Y=np.array([(lambda X: X[i][2][0] + X[i][2][1])(X) for i in range(len(X))])

In [75]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 2)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)

test_input = array([[8, 51],
                    [11,56],
                    [14,61]])

test_input = test_input.reshape((1, 3, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)


Epoch 1/100
1/1 [==============================] - 0s 189ms/step - loss: 38909.8086 - val_loss: 140949.2344
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 38020.2227 - val_loss: 136296.1250
Epoch 3/100
1/1 [==============================] - 0s 15ms/step - loss: 36989.3477 - val_loss: 130932.4375
Epoch 4/100
1/1 [==============================] - 0s 16ms/step - loss: 35838.1875 - val_loss: 125520.8125
Epoch 5/100
1/1 [==============================] - 0s 15ms/step - loss: 34602.9570 - val_loss: 120633.6484
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 33297.8008 - val_loss: 115293.6250
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 31857.6035 - val_loss: 107771.4141
Epoch 8/100
1/1 [==============================] - 0s 19ms/step - loss: 30294.4121 - val_loss: 102262.6484
Epoch 9/100
1/1 [==============================] - 0s 14ms/step - loss: 28957.3691 - val_loss: 99165.5547
Epoch 10/100
1/1 [===================

Epoch 79/100
1/1 [==============================] - 0s 19ms/step - loss: 51.6807 - val_loss: 103.4851
Epoch 80/100
1/1 [==============================] - 0s 16ms/step - loss: 41.9522 - val_loss: 76.4302
Epoch 81/100
1/1 [==============================] - 0s 17ms/step - loss: 32.0749 - val_loss: 48.1702
Epoch 82/100
1/1 [==============================] - 0s 17ms/step - loss: 22.4225 - val_loss: 18.2342
Epoch 83/100
1/1 [==============================] - 0s 16ms/step - loss: 13.9656 - val_loss: 0.0943
Epoch 84/100
1/1 [==============================] - 0s 18ms/step - loss: 10.0294 - val_loss: 28.9679
Epoch 85/100
1/1 [==============================] - 0s 14ms/step - loss: 15.1374 - val_loss: 45.6732
Epoch 86/100
1/1 [==============================] - 0s 16ms/step - loss: 18.7544 - val_loss: 37.4350
Epoch 87/100
1/1 [==============================] - 0s 16ms/step - loss: 17.8226 - val_loss: 18.4470
Epoch 88/100
1/1 [==============================] - 0s 16ms/step - loss: 14.5232 - val_loss

In [78]:
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(3, 2)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)

test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
1/1 [==============================] - 1s 545ms/step - loss: 31201.3145 - val_loss: 113262.7500
Epoch 2/100
1/1 [==============================] - 0s 15ms/step - loss: 31195.6797 - val_loss: 113223.6016
Epoch 3/100
1/1 [==============================] - 0s 17ms/step - loss: 31187.7988 - val_loss: 113177.5000
Epoch 4/100
1/1 [==============================] - 0s 20ms/step - loss: 31176.4551 - val_loss: 113117.9766
Epoch 5/100
1/1 [==============================] - 0s 17ms/step - loss: 31161.8125 - val_loss: 113048.5703
Epoch 6/100
1/1 [==============================] - 0s 17ms/step - loss: 31143.6406 - val_loss: 112951.1953
Epoch 7/100
1/1 [==============================] - 0s 20ms/step - loss: 31119.4277 - val_loss: 112772.7109
Epoch 8/100
1/1 [==============================] - 0s 15ms/step - loss: 31083.5215 - val_loss: 112529.5000
Epoch 9/100
1/1 [==============================] - 0s 18ms/step - loss: 31031.2266 - val_loss: 112211.8203
Epoch 10/100
1/1 [==================

1/1 [==============================] - 0s 33ms/step - loss: 7.2657 - val_loss: 0.4358
Epoch 81/100
1/1 [==============================] - 0s 22ms/step - loss: 6.9977 - val_loss: 0.1952
Epoch 82/100
1/1 [==============================] - 0s 21ms/step - loss: 5.9639 - val_loss: 1.7402
Epoch 83/100
1/1 [==============================] - 0s 18ms/step - loss: 4.8130 - val_loss: 6.7151
Epoch 84/100
1/1 [==============================] - 0s 22ms/step - loss: 4.2878 - val_loss: 12.3826
Epoch 85/100
1/1 [==============================] - 0s 28ms/step - loss: 4.2299 - val_loss: 14.1761
Epoch 86/100
1/1 [==============================] - 0s 46ms/step - loss: 3.8998 - val_loss: 11.0357
Epoch 87/100
1/1 [==============================] - 0s 26ms/step - loss: 3.1093 - val_loss: 6.0444
Epoch 88/100
1/1 [==============================] - 0s 22ms/step - loss: 2.3434 - val_loss: 2.4861
Epoch 89/100
1/1 [==============================] - 0s 24ms/step - loss: 1.9853 - val_loss: 1.0587
Epoch 90/100
1/1 [==

In [80]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 2)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
1/1 [==============================] - 0s 277ms/step - loss: 32437.2754 - val_loss: 116127.8750
Epoch 2/100
1/1 [==============================] - 0s 14ms/step - loss: 31768.5723 - val_loss: 113260.3516
Epoch 3/100
1/1 [==============================] - 0s 13ms/step - loss: 31043.7363 - val_loss: 110642.7500
Epoch 4/100
1/1 [==============================] - 0s 15ms/step - loss: 30290.4473 - val_loss: 108142.8984
Epoch 5/100
1/1 [==============================] - 0s 17ms/step - loss: 29489.0625 - val_loss: 104990.7266
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 28567.5684 - val_loss: 101043.4766
Epoch 7/100
1/1 [==============================] - 0s 14ms/step - loss: 27549.7324 - val_loss: 97815.2109
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 26540.6113 - val_loss: 94168.5703
Epoch 9/100
1/1 [==============================] - 0s 13ms/step - loss: 25457.6250 - val_loss: 88996.6016
Epoch 10/100
1/1 [=====================

Epoch 80/100
1/1 [==============================] - 0s 16ms/step - loss: 5.3294 - val_loss: 2.7152
Epoch 81/100
1/1 [==============================] - 0s 15ms/step - loss: 4.9346 - val_loss: 8.7612
Epoch 82/100
1/1 [==============================] - 0s 15ms/step - loss: 4.6386 - val_loss: 10.3471
Epoch 83/100
1/1 [==============================] - 0s 16ms/step - loss: 4.3880 - val_loss: 6.7525
Epoch 84/100
1/1 [==============================] - 0s 16ms/step - loss: 4.1926 - val_loss: 7.3295
Epoch 85/100
1/1 [==============================] - 0s 22ms/step - loss: 4.0527 - val_loss: 11.3212
Epoch 86/100
1/1 [==============================] - 0s 16ms/step - loss: 3.9699 - val_loss: 10.2468
Epoch 87/100
1/1 [==============================] - 0s 16ms/step - loss: 3.8500 - val_loss: 7.6750
Epoch 88/100
1/1 [==============================] - 0s 15ms/step - loss: 3.7314 - val_loss: 10.4427
Epoch 89/100
1/1 [==============================] - 0s 15ms/step - loss: 3.5671 - val_loss: 13.4823
Epoch

In [81]:
# many to one case where we want one output for each feature in the time-step
Y = list()
for x in X:
    new_item = list()
    new_item.append(x[2][0]+3)
    new_item.append(x[2][1]+5)
    Y.append(new_item)

Y = np.array(Y)
print(Y)

[[ 12  20]
 [ 21  35]
 [ 30  50]
 [ 39  65]
 [ 48  80]
 [ 57  95]
 [ 66 110]
 [ 75 125]
 [ 84 140]
 [ 93 155]
 [102 170]
 [111 185]
 [120 200]
 [129 215]
 [138 230]]


In [82]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 2)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)

Epoch 1/100
1/1 [==============================] - 1s 642ms/step - loss: 9502.6924 - val_loss: 32987.6211
Epoch 2/100
1/1 [==============================] - 0s 57ms/step - loss: 9275.5010 - val_loss: 32060.7910
Epoch 3/100
1/1 [==============================] - 0s 45ms/step - loss: 9039.7656 - val_loss: 31029.2520
Epoch 4/100
1/1 [==============================] - 0s 46ms/step - loss: 8795.2256 - val_loss: 29959.5684
Epoch 5/100
1/1 [==============================] - 0s 47ms/step - loss: 8548.4336 - val_loss: 28954.8340
Epoch 6/100
1/1 [==============================] - 0s 48ms/step - loss: 8309.7910 - val_loss: 28100.4434
Epoch 7/100
1/1 [==============================] - 0s 55ms/step - loss: 8087.5991 - val_loss: 27412.8203
Epoch 8/100
1/1 [==============================] - 0s 47ms/step - loss: 7884.8657 - val_loss: 26834.0527
Epoch 9/100
1/1 [==============================] - 0s 47ms/step - loss: 7695.8359 - val_loss: 26284.9277
Epoch 10/100
1/1 [==============================] - 0s

In [83]:
test_input = array([[20,34],
                    [23,39],
                    [26,44]])

test_input = test_input.reshape((1, 3, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[29.275103 49.783188]]


In [85]:
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(3, 2)))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)

test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 8980.4883 - val_loss: 31560.8594
Epoch 2/100
1/1 [==============================] - 0s 35ms/step - loss: 8975.0654 - val_loss: 31547.0254
Epoch 3/100
1/1 [==============================] - 0s 37ms/step - loss: 8969.8486 - val_loss: 31537.9590
Epoch 4/100
1/1 [==============================] - 0s 38ms/step - loss: 8967.9219 - val_loss: 31534.6152
Epoch 5/100
1/1 [==============================] - 0s 37ms/step - loss: 8967.3916 - val_loss: 31527.4004
Epoch 6/100
1/1 [==============================] - 0s 38ms/step - loss: 8966.1221 - val_loss: 31504.2988
Epoch 7/100
1/1 [==============================] - 0s 40ms/step - loss: 8961.9219 - val_loss: 31479.4062
Epoch 8/100
1/1 [==============================] - 0s 36ms/step - loss: 8955.6299 - val_loss: 31461.3906
Epoch 9/100
1/1 [==============================] - 0s 45ms/step - loss: 8949.9697 - val_loss: 31440.6621
Epoch 10/100
1/1 [==============================] - 0s 40

In [86]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 2)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
1/1 [==============================] - 1s 987ms/step - loss: 10514.7207 - val_loss: 35932.2539
Epoch 2/100
1/1 [==============================] - 0s 22ms/step - loss: 10226.0127 - val_loss: 34822.4180
Epoch 3/100
1/1 [==============================] - 0s 30ms/step - loss: 9951.3164 - val_loss: 33907.7344
Epoch 4/100
1/1 [==============================] - 0s 29ms/step - loss: 9703.5137 - val_loss: 33122.4023
Epoch 5/100
1/1 [==============================] - 0s 30ms/step - loss: 9481.0811 - val_loss: 32387.7246
Epoch 6/100
1/1 [==============================] - 0s 31ms/step - loss: 9272.0225 - val_loss: 31683.7188
Epoch 7/100
1/1 [==============================] - 0s 30ms/step - loss: 9070.4873 - val_loss: 31005.2793
Epoch 8/100
1/1 [==============================] - 0s 30ms/step - loss: 8873.8066 - val_loss: 30347.1973
Epoch 9/100
1/1 [==============================] - 0s 34ms/step - loss: 8680.1182 - val_loss: 29701.9766
Epoch 10/100
1/1 [==============================] - 

In [8]:
# one to many with single feature
X = list()
Y = list()
X = [x+3 for x in range(-2, 43, 3)]

for i in X:
    output_vector = list()
    output_vector.append(i+1)
    output_vector.append(i+2)
    Y.append(output_vector)

print(X)
print(Y)

X = np.array(X).reshape(15, 1, 1)
Y = np.array(Y)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43]
[[2, 3], [5, 6], [8, 9], [11, 12], [14, 15], [17, 18], [20, 21], [23, 24], [26, 27], [29, 30], [32, 33], [35, 36], [38, 39], [41, 42], [44, 45]]


In [12]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 1)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(X, Y, epochs=100, validation_split=0.2, batch_size=3)

test_input = array([10])
test_input = test_input.reshape((1, 1, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(1, 1)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1, batch_size=3)

test_output = model.predict(test_input, verbose=0)
print(test_output)

from tensorflow.keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(1, 1)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1, batch_size=3)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
4/4 [==============================] - 1s 236ms/step - loss: 429.8820 - val_loss: 1550.6732
Epoch 2/100
4/4 [==============================] - 0s 13ms/step - loss: 423.6541 - val_loss: 1527.2133
Epoch 3/100
4/4 [==============================] - 0s 11ms/step - loss: 417.0865 - val_loss: 1502.4603
Epoch 4/100
4/4 [==============================] - 0s 10ms/step - loss: 410.3382 - val_loss: 1474.9801
Epoch 5/100
4/4 [==============================] - 0s 10ms/step - loss: 402.8879 - val_loss: 1444.8717
Epoch 6/100
4/4 [==============================] - 0s 10ms/step - loss: 394.9902 - val_loss: 1411.3280
Epoch 7/100
4/4 [==============================] - 0s 15ms/step - loss: 386.6557 - val_loss: 1373.9049
Epoch 8/100
4/4 [==============================] - 0s 9ms/step - loss: 376.4530 - val_loss: 1333.7628
Epoch 9/100
4/4 [==============================] - 0s 11ms/step - loss: 367.4108 - val_loss: 1288.7833
Epoch 10/100
4/4 [==============================] - 0s 10ms/step - loss: 

[[8.6439905 8.660675 ]]
Epoch 1/100
4/4 [==============================] - 1s 265ms/step - loss: 466.5866 - val_loss: 1719.1007
Epoch 2/100
4/4 [==============================] - 0s 8ms/step - loss: 464.4266 - val_loss: 1712.5684
Epoch 3/100
4/4 [==============================] - 0s 9ms/step - loss: 462.3593 - val_loss: 1704.7490
Epoch 4/100
4/4 [==============================] - 0s 10ms/step - loss: 459.5469 - val_loss: 1695.1387
Epoch 5/100
4/4 [==============================] - 0s 9ms/step - loss: 456.2471 - val_loss: 1681.9307
Epoch 6/100
4/4 [==============================] - 0s 9ms/step - loss: 453.0281 - val_loss: 1663.6820
Epoch 7/100
4/4 [==============================] - 0s 10ms/step - loss: 447.4276 - val_loss: 1638.7924
Epoch 8/100
4/4 [==============================] - 0s 10ms/step - loss: 439.1081 - val_loss: 1605.1898
Epoch 9/100
4/4 [==============================] - 0s 14ms/step - loss: 428.9996 - val_loss: 1557.5020
Epoch 10/100
4/4 [==============================] - 

Epoch 49/100
4/4 [==============================] - 0s 7ms/step - loss: 4.3102 - val_loss: 14.3050
Epoch 50/100
4/4 [==============================] - 0s 7ms/step - loss: 4.2708 - val_loss: 14.4220
Epoch 51/100
4/4 [==============================] - 0s 8ms/step - loss: 4.2283 - val_loss: 14.7192
Epoch 52/100
4/4 [==============================] - 0s 8ms/step - loss: 4.1887 - val_loss: 14.5291
Epoch 53/100
4/4 [==============================] - 0s 8ms/step - loss: 4.1528 - val_loss: 14.8138
Epoch 54/100
4/4 [==============================] - 0s 8ms/step - loss: 4.1117 - val_loss: 14.7863
Epoch 55/100
4/4 [==============================] - 0s 8ms/step - loss: 4.0730 - val_loss: 14.8055
Epoch 56/100
4/4 [==============================] - 0s 8ms/step - loss: 4.0306 - val_loss: 14.4018
Epoch 57/100
4/4 [==============================] - 0s 8ms/step - loss: 3.9944 - val_loss: 14.2926
Epoch 58/100
4/4 [==============================] - 0s 7ms/step - loss: 3.9508 - val_loss: 13.8212
Epoch 59/1

In [18]:
# one to many with multiple features
nums = 25

X1 = list()
X2 = list()
X = list()
Y = list()

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]

for x1, x2 in zip(X1, X2):
    output_vector = list()
    output_vector.append(x1+1)
    output_vector.append(x2+1)
    Y.append(output_vector)

X = np.column_stack((X1, X2))
#print(X)

X = np.array(X).reshape(25, 1, 2)
Y = np.array(Y)

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 2)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(X, Y, epochs=100, validation_split=0.2, batch_size=3)

test_input = array([40, 60])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(1, 2)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1, batch_size=3)

test_input = array([40, 60])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)


model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(1, 2)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1, batch_size=3)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/100
7/7 [==============================] - 1s 79ms/step - loss: 905.1554 - val_loss: 3140.6277
Epoch 2/100
7/7 [==============================] - 0s 6ms/step - loss: 865.9722 - val_loss: 3003.8579
Epoch 3/100
7/7 [==============================] - 0s 7ms/step - loss: 830.9038 - val_loss: 2872.6907
Epoch 4/100
7/7 [==============================] - 0s 7ms/step - loss: 789.1575 - val_loss: 2748.7410
Epoch 5/100
7/7 [==============================] - 0s 7ms/step - loss: 749.5898 - val_loss: 2605.7136
Epoch 6/100
7/7 [==============================] - 0s 6ms/step - loss: 707.8474 - val_loss: 2413.4187
Epoch 7/100
7/7 [==============================] - 0s 7ms/step - loss: 646.4099 - val_loss: 2157.2388
Epoch 8/100
7/7 [==============================] - 0s 6ms/step - loss: 574.1957 - val_loss: 1843.3258
Epoch 9/100
7/7 [==============================] - 0s 7ms/step - loss: 484.9339 - val_loss: 1518.7356
Epoch 10/100
7/7 [==============================] - 0s 7ms/step - loss: 410.3751 

Epoch 84/100
7/7 [==============================] - 0s 6ms/step - loss: 1.5940 - val_loss: 1.5011
Epoch 85/100
7/7 [==============================] - 0s 6ms/step - loss: 1.5745 - val_loss: 1.2899
Epoch 86/100
7/7 [==============================] - 0s 6ms/step - loss: 1.5585 - val_loss: 1.1535
Epoch 87/100
7/7 [==============================] - 0s 7ms/step - loss: 1.5449 - val_loss: 1.0898
Epoch 88/100
7/7 [==============================] - 0s 7ms/step - loss: 1.5243 - val_loss: 1.3178
Epoch 89/100
7/7 [==============================] - 0s 7ms/step - loss: 1.5111 - val_loss: 1.5092
Epoch 90/100
7/7 [==============================] - 0s 6ms/step - loss: 1.4864 - val_loss: 1.3821
Epoch 91/100
7/7 [==============================] - 0s 6ms/step - loss: 1.4749 - val_loss: 1.1023
Epoch 92/100
7/7 [==============================] - 0s 9ms/step - loss: 1.4581 - val_loss: 1.0047
Epoch 93/100
7/7 [==============================] - 0s 7ms/step - loss: 1.4338 - val_loss: 1.1569
Epoch 94/100
7/7 [==

[[41.629787 61.911396]]
Epoch 1/100
7/7 [==============================] - 1s 130ms/step - loss: 987.7256 - val_loss: 3550.6296
Epoch 2/100
7/7 [==============================] - 0s 8ms/step - loss: 974.5079 - val_loss: 3502.3203
Epoch 3/100
7/7 [==============================] - 0s 8ms/step - loss: 961.4678 - val_loss: 3418.2280
Epoch 4/100
7/7 [==============================] - 0s 8ms/step - loss: 937.8309 - val_loss: 3271.0786
Epoch 5/100
7/7 [==============================] - 0s 8ms/step - loss: 893.6589 - val_loss: 3042.9824
Epoch 6/100
7/7 [==============================] - 0s 8ms/step - loss: 831.2165 - val_loss: 2691.8230
Epoch 7/100
7/7 [==============================] - 0s 8ms/step - loss: 732.6320 - val_loss: 2234.5945
Epoch 8/100
7/7 [==============================] - 0s 7ms/step - loss: 584.0366 - val_loss: 1678.7859
Epoch 9/100
7/7 [==============================] - 0s 8ms/step - loss: 408.2905 - val_loss: 1000.9673
Epoch 10/100
7/7 [==============================] - 0s 1

7/7 [==============================] - 0s 9ms/step - loss: 0.1493 - val_loss: 0.7553
Epoch 77/100
7/7 [==============================] - 0s 7ms/step - loss: 0.1451 - val_loss: 0.6509
Epoch 78/100
7/7 [==============================] - 0s 10ms/step - loss: 0.1420 - val_loss: 0.5667
Epoch 79/100
7/7 [==============================] - 0s 10ms/step - loss: 0.1402 - val_loss: 0.5625
Epoch 80/100
7/7 [==============================] - 0s 8ms/step - loss: 0.1386 - val_loss: 0.5247
Epoch 81/100
7/7 [==============================] - 0s 8ms/step - loss: 0.1328 - val_loss: 0.6327
Epoch 82/100
7/7 [==============================] - 0s 8ms/step - loss: 0.1319 - val_loss: 0.6280
Epoch 83/100
7/7 [==============================] - 0s 8ms/step - loss: 0.1263 - val_loss: 0.5091
Epoch 84/100
7/7 [==============================] - 0s 8ms/step - loss: 0.1259 - val_loss: 0.6328
Epoch 85/100
7/7 [==============================] - 0s 8ms/step - loss: 0.1202 - val_loss: 0.5293
Epoch 86/100
7/7 [=============

7/7 [==============================] - 0s 8ms/step - loss: 0.1903 - val_loss: 0.0529
Epoch 52/100
7/7 [==============================] - 0s 6ms/step - loss: 0.1769 - val_loss: 0.0207
Epoch 53/100
7/7 [==============================] - 0s 6ms/step - loss: 0.1671 - val_loss: 0.0207
Epoch 54/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1560 - val_loss: 0.0254
Epoch 55/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1507 - val_loss: 0.0187
Epoch 56/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1418 - val_loss: 0.0219
Epoch 57/100
7/7 [==============================] - 0s 6ms/step - loss: 0.1314 - val_loss: 0.0123
Epoch 58/100
7/7 [==============================] - 0s 8ms/step - loss: 0.1262 - val_loss: 0.0100
Epoch 59/100
7/7 [==============================] - 0s 7ms/step - loss: 0.1184 - val_loss: 0.0104
Epoch 60/100
7/7 [==============================] - 0s 12ms/step - loss: 0.1120 - val_loss: 0.0113
Epoch 61/100
7/7 [==============

In [20]:
# many to many sequence problem with single feature
X = [x for x in range(5, 301, 5)]
Y = [y for y in range(20, 316, 5)]

# 3D format of input/output fpr encoder-decoder
X = np.array(X).reshape(20, 3, 1)
Y = np.array(Y).reshape(20, 3, 1)

