In [3]:
import tensorflow as tf
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [75]:
# tensor are nD arrays with uniform "dtype" So all elemnets are of same dtypr in ths list
# check dtype of tensor as tf.

# rank 0 tensor/scalar
tf.constant(0)

# rank 1 tensor
tf.constant([2.0,3.0,4.0])

# rank 2 tensor -> 2 axis. If you want to be specific, you can put dtype also
tf.constant([[1,2],
             [3,4]], dtype=tf.float32)

# rank 3 tensor
rank_3_tensor = tf.constant(
    [
     [[1,2,4],
      [2,1,4]],
     [[2,3,4],
      [4,3,2]],
     [[5,6,7],
      [7,6,5]]
     ])
    
# tensor -> numpy using np.array(tensor) OR tensor.numpy()    
np.array(tf.constant([2.0,3.0,4.0]))
tf.constant([2.0,3.0,4.0]).numpy()

# numpy ->array using tf.convert_to_tensor
tf.convert_to_tensor(tf.constant([2.0,3.0,4.0]).numpy())

# if you don't specify dtype, it choses it from data. int goes to tf.int32 and float to tf,float32
# use tf.cast(tensor,dtype) to change it later

<tf.Tensor: shape=(), dtype=int32, numpy=0>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

array([2., 3., 4.], dtype=float32)

array([2., 3., 4.], dtype=float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [22]:
# basic math ops
a = tf.constant([[1,2],
                 [3,4]])
b = tf.ones([2,2],dtype=tf.int32)
#tf.add(a,b) or a + b
#tf.multiply(a,b) or a * b element wise
#tf matmul(a,b) or a @ b

#largest value
tf.reduce_max(a)

#index of largest value
tf.argmax(a)

# compute softmax
tf.nn.softmax(tf.cast(a,tf.float32))

<tf.Tensor: shape=(), dtype=int32, numpy=4>

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.26894143, 0.7310586 ],
       [0.26894143, 0.7310586 ]], dtype=float32)>

In [34]:
# shape -> length of each dimension of a tensor
# rank -> number of dimension
# axis/dim -> particular dim
# size -> total number of elements

rank_4_tensor = tf.zeros([3,2,4,5])
# rank 4 -> axis=0,1,2,3 (or -1)
# batch, width, height, features

rank_4_tensor.dtype
rank_4_tensor.ndim
rank_4_tensor.shape
rank_4_tensor.shape[3]
tf.size(rank_4_tensor).numpy()
np.array(tf.size(rank_4_tensor))

tf.float32

4

TensorShape([3, 2, 4, 5])

5

120

array(120)

In [54]:
# indexing
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
rank_1_tensor[:2].numpy().tolist()
rank_1_tensor[::2].numpy().tolist() #every other item

# multi-axis indexing
rank_2_tensor = tf.constant([
                             [1,2],
                             [3,4],
                             [5,6]])
rank_2_tensor.shape.as_list()
rank_2_tensor[1,1].numpy()
rank_2_tensor[-1,:].numpy().tolist()

[0, 1]

[0, 1, 3, 8, 21]

[3, 2]

4

[5, 6]

In [68]:
x = tf.constant([[1],[2],[3]])
x.shape
x.shape.as_list()

rank_3_tensor = tf.constant([[[ 0 ,1,  2,  3,  4],
  [ 5,  6,  7,  8,  9]],

 [[10, 11, 12, 13, 14],
  [15, 16, 17, 18, 19]],

 [[20, 21, 22, 23, 24],
  [25, 26, 27, 28, 29]]])

rank_3_tensor.shape

#some nice reshapes. Reshape shape has to be sent in a list
tf.reshape(rank_3_tensor,[3*2,5])
tf.reshape(rank_3_tensor,[3,2*5])

#to check order of filling, flatten the tensor. -1 means whatever fits in
tf.reshape(rank_3_tensor,[-1])

# swapping axes do not not in reshape. Use transpose for that

TensorShape([3, 1])

[3, 1]

TensorShape([3, 2, 5])

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])>

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])>

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>

In [73]:
# Broadcasting
x = tf.range(1,4)
y = tf.constant(2)
x
y
x*y

# Remember shape [1,4] <-> [4,] <-> [4] leading one can be omitted in shape
# to check broadcasting look like, use tf.broadcast_to()
tf.broadcast_to(tf.constant([1,2,3]),[3,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

<tf.Tensor: shape=(), dtype=int32, numpy=2>

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [77]:
# Ragged tensor (tensor with not rectangular shape.. so have unknown dim)
Ragged_list = [[0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]
tf.ragged.constant(Ragged_list)
tf.ragged.constant(Ragged_list).shape

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

TensorShape([4, None])

In [85]:
# String tensor dtype =tf.string
tf.constant("Gray wolf") #b stands for byte string.. so not a unicode text
tf.constant("🥳👍") #-> unocode goes to utf8 encoded answer

scalar_string_tensor = tf.constant(["Krunal","Gedia"])
tf.strings.split(scalar_string_tensor, sep=" ") 
#be careful, you can land up with ragged tensor

text = tf.constant("1 10 100")
tf.strings.to_number(tf.strings.split(text, sep=" "))

<tf.Tensor: shape=(), dtype=string, numpy=b'Gray wolf'>

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

<tf.RaggedTensor [[b'Krunal'], [b'Gedia']]>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  1.,  10., 100.], dtype=float32)>

In [88]:
# Sparse tensor
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# sparse to dense form
tf.sparse.to_dense(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 



<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]])>